### ISSUE TITLE
Pie chart documentation

### ISSUE THREAD

**Issue by nielsrolf** [man-group/dtale#110]
Hi,
I am not sure how to use the pie chart - why does it have an x and y axis?
In case there is a better channel for support questions like this, let me know.

And thanks for the project!

**Comment by aschonfeld** [comment]
No worries, this channel is totally fine.  So the only reason why the input labels for pie charts are x & y axis just like everything else is because I didn't want to add a bunch of custom logic just for input labels (but if it becomes too confusing I can certainly do that :).

The way to think about the inputs for a pie chart is that the x-axis will drive the names of the slices of the pie and the y-axis will drive the sizes of the slices.

So if you have two columns (country & population size) then the x-axis would be country and the y-axis would population size and the there would be a slice for each country and the size of the slice would be driven by its value for population size.

If you have duplicate entries for a country then you will also have to specify a value for *Agg* and one example would be to use `sum` which will just group on country and then sum its values for population size.

Hope this helps!

**Comment by nielsrolf** [comment]
Great makes sense!
Maybe it's clearer if the x-axis would be called `groupby` axis, just as an idea :)

**Comment by aschonfeld** [comment]
Good idea!  I’ll see if I can maybe fit it underneath the “X” label in parenthesis 👍
