### ISSUE TITLE
Feature request: select only most relevant groups in a groupby chart with too many categories

### ISSUE THREAD

**Issue by nielsrolf** [man-group/dtale#112]
I would like to plot revenue over time for different products in a dataset I am exploring. For this, I chose the bar chart with:
- x-axis: date
- y-axis: price
- groupby: product
- aggregate: sum
Then, I get the following error message: Group (product) contains more than 30 unique values, please add additional filtering or else chart will be unreadable.

It would be great to easily select only those groups with the largest value, if the aggregation is applied to the whole group (and disregarding the x-axis).

**Comment by aschonfeld** [comment]
@nielsrolf I think I'll need some more help from you on requirements for this change.  I like the idea, but it's easy to run into issues figuring out the top 30 groups if your x-axis has more than one value.  Would just take the sum of each of the groups over the x-axis and find the ones with the 30 largest sums?

Also, would it be possible to use a different chart to show this data?  Like a 3D chart like heatmap, 3D Scatter or Surface?

You could try those charts with the following configuration:
* x-axis -> date
* y-axis -> product
* z-axis -> price
* agg -> sum

Those charts have no limit on groups.  It make not be what you want, but give it a shot 🤞

**Comment by nielsrolf** [comment]
Maybe it's clearer in code:

```Python
categories = df.groupby(groupby)\
    .aggregate({y_axis: agg})\
    .sort_values(y_axis)
other_categories = categories[:-max_num_categories+1].index
chart_df = df[[groupby]].replace(other_categories, 'Other')\
    .join( df[[c for c in df.columns if c != groupby]])
```

I would do this as (optional) preprocessing for the bar chart, so I would use the aggregation method that is defined for the x-axis, and then take the groupby-keys with the lowest values and combine them to a new group 'Other'.

**Comment by aschonfeld** [comment]
@nielsrolf  This is pure brilliance.  I think this is a great idea.  So rather than protect people from producing unreadable charts we simply bundle all the other (most likely insignificant groups) into one bucket.  Brilliant!

I couldn't really picture how this would work before because of the x-axis selection, but if you ignore it and simply focus on the grouping & y-axis then you can produce a value that you can rank the groups on.  Now I'm sure there's probably a way to do this ranking because what if you care about the 30 worst groups. With your logic we'd bundle those into "Other".  So what if change the selection logic to take the 15 highest & 15 lowest?

I can also add a little message to the top of the chart (similar to what I do for negative values that accidentally get passed into pie charts) showing which groups are in "Other"

**Comment by aschonfeld** [comment]
So I have the logic working, with the exception I can't display the "Other" bucket yet because the logic kind of falls over if you're grouping on multiple columns so I'm just dropping it for now.  The other issue is that if you have multiple y-axis its simply basing the top & bottom 30 groups on the first y-axis sepcified.  Still kind of looks unreadable, but my laptop is pretty small.

![image](https://user-images.githubusercontent.com/11547371/77498301-aa67dc00-6e25-11ea-86a7-7a38bc5f9048.png)

**Comment by nielsrolf** [comment]
Nice!
I am thinking if I can contribute a little bit and for example see if I can make the number of categories adjustable or if I find a solution on how to display the 'Other' category. Is there a 'getting started with the code base' document? Or maybe it's already enough if you link to the commit where you implemented this, I couldn't find it.

**Comment by aschonfeld** [comment]
@nielsrolf so I created this branch for the current state of the changes: https://github.com/man-group/dtale/tree/feature/112

Certainly not in a final state and I'm still not certain how we'll handle the multiple y-axis scenario.  Also, for trying to get the "Other" group to show up there will  have to be some changes made when you are grouping on multiple columns.

For example:
group = [str_col, int_col] then other will have to be something like ["Other", 0] so it will also be driven by data types of the columns in the grouping.

**Comment by aschonfeld** [comment]
@nielsrolf I meant to update you on this.  I've had a lot of trouble wrapping my head around a convenient way to select the most relevant groups so in the meantime I've added a new way to select groups when building charts: https://youtu.be/v0XAmHqTKho

So it will still prompt you with an exception if you have more than 30 (and haven't selected anything from the "Group(s)" dropdown) and list all the groups available, but then you can start selecting which ones you want to see and toggle each one on & off at your leisure.  Not totally ideal, but much easier than building query strings.  Hope this helps!

**Comment by nielsrolf** [comment]
Great solution - it makes the feature useful for fast exploratory analysis! Sorry for the late response, I got cought up in a lot of work, and I didn't find the time to get into the code base. But again thanks for the great project!

**Comment by aschonfeld** [comment]
Terrific, should I close this or keep it open on the off chance we do come up with a more intuitive way of selecting default groups when there is more than 30?

**Comment by nielsrolf** [comment]
I would close it for now
