### ISSUE TITLE
correlations window

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#116]
1- The window opens out of the monitor screen
2-There is two "<> Code Export" in that window the top one doesn't work

**Comment by aschonfeld** [comment]
So the reason for opening out of the main tab is because the popup is quite large and I didn't want to block user's view of the main grid.  If you think opening a new tab rather than a popup window for correlations I can do that.

I'll take a look at the code export buttons.  Good catch :)

**Comment by aschonfeld** [comment]
Ok, I see the issue with the top code export button.  So its no longer clickable on the demo because the "Fork me on Github" link is actually blocking it.  I can look into trying to fix that or even maybe using a different icon that will go in the bottom right-hand corner.  I don't want to limit it completely because I need my stars :) since that's what my superiors use to measure whether working on D-Tale is time well spent or not. :(

**Comment by aschonfeld** [comment]
The best I could do was making the icon smaller so that now you have the ability to click on the html icon & the "Co"
![image](https://user-images.githubusercontent.com/11547371/77571551-ef325800-6ea3-11ea-9677-ce167ab51e73.png)

**Comment by aschonfeld** [comment]
fixed in v1.8.1
