### ISSUE TITLE
Map Chart

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#118]
There is huge potential on the map chart. It can be based on some free online maps or GeoJSON files. Plotly has an interesting map plot.
i.e. https://plotly.com/python/scatter-plots-on-maps/

**Comment by aschonfeld** [comment]
I added "Maps" chart type as an option, but the data you supplied on houses seems to only have data for the northwest corner of washington so it produces kind of a dull map. :(

Need some more global data or at least data from around the entire US

**Comment by reza1615** [comment]
in the map chart window please link to geojson links to download. and based on downloaded file path it can generate the map

**Comment by reza1615** [comment]
here is the list of USA airports we can use their lat and long
https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv

**Comment by reza1615** [comment]
I updated Lat and Long in the CSV file to have whole USA cities also added deltatime dtype. please use this zip file.
[kc_house_data_2.zip](https://github.com/man-group/dtale/files/4400307/kc_house_data_2.zip)

**Comment by aschonfeld** [comment]
Looks like there still might be an issue with your lat/long values.  This shows that they extend all the way to the north pole!

![image](https://user-images.githubusercontent.com/11547371/77871891-7caed880-7213-11ea-9b14-b82310d793a4.png)

Sorry the kids had me watching Polar Express today :)

**Comment by reza1615** [comment]
I had only 52 airports in all states so for the rest I added some random change to the lat and long.
try to filter them and only get 100-200 cases

**Comment by reza1615** [comment]
I updated the file. Now I added USA cities and states. you can test your code by state column.
also, I included 320K cities in USA in another file.
[03.zip](https://github.com/man-group/dtale/files/4400733/03.zip)

**Comment by reza1615** [comment]
Just as FYI. For Lat and Long I found this link http://download.geonames.org/export/dump/
It hosted all countries lat and long.

**Comment by reza1615** [comment]
For map chart would you please use mapbox. It has more details and different maps.
https://plotly.com/python/scattermapbox/


based on below link if you set layout.mapbox.style properly it doesn't need token like
https://plotly.com/python/mapbox-layers/

![image](https://user-images.githubusercontent.com/2202483/78253551-932e8b80-74c2-11ea-82e6-af4243f03c4f.png)

**Comment by aschonfeld** [comment]
I can add scattermapbox to the "Map Type" drop-down.  Nice find.  Not sure how performant it will be but I'll def include it.

Just a heads up, anything that requires loading from the internet might be a while because this tool was supposed to be something that didn't require outside network connections.  That being said I think if I present the user with a clear enough exception when they don't have a connection to the outside world it should be fine.

**Comment by reza1615** [comment]
For offline support we should have access to GEOJSON to upload customized map. now offline map only have world (without country, state borders) + USA

**Comment by aschonfeld** [comment]
@reza1615 I've added the following static files to the app so that offline map generation is now possible (with some major hacking to plotly's JS as well 😉 )

* Scope -> world, Location Type -> ISO-3, country names: **world_110m.json**
* Scope -> usa, Location Type -> USA-states: **usa_110m.json 67ms**
* Scope -> europe: **europe_110m.json**
* Scope -> asia -> **asia_110m.json**
* Scope -> africa -> **africa_110m.json**
* Scope -> north america -> **north-america_110m.json**
* Scope -> south america -> **south-america_110m.json**

I'll create a separate ticket for allowing users to load their own custom topojson files..

**Comment by reza1615** [comment]
Asia and world json has bug see the in github

**Comment by aschonfeld** [comment]
added v1.8.3
