### ISSUE TITLE
Build column, Random, Date selecting Include Timestamp doesn't update code snippet

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#128]
When I select **Include Timestamps** in  Build column> Random>Date It doesn't update the below code.

![image](https://user-images.githubusercontent.com/2202483/77839836-71de4000-714e-11ea-9dfa-df37fa6a0afd.png)

**Comment by aschonfeld** [comment]
Unfortunately the reason for that is because there is so much code involved in building the random timestamps that I couldn't really show it.  I can change it to show a message that you can see this code once you've added the column and click "Code Export" from the main menu.

Here is the code that gets used:
```
def pp(start, end, n):
    start_u = start.value // 10 ** 9
    end_u = end.value // 10 ** 9
    return pd.DatetimeIndex(
        (10 ** 9 * np.random.randint(start_u, end_u, n)).view('M8[ns]')
    )

dates = pp(pd.Timestamp(start), pd.Timestamp(end), len(data))
```

**Comment by reza1615** [comment]
or push the code at there and add a **See more** button to hide huge codes.

**Comment by aschonfeld** [comment]
Here's what I got 
![image](https://user-images.githubusercontent.com/11547371/78045935-8a17b000-7344-11ea-9dc7-1eb21245a16c.png)

**Comment by reza1615** [comment]
you made it with mouseover. is it possible to select and copy/paste the code?

**Comment by aschonfeld** [comment]
Yes if you move your mouse through the little triangle at the top it will stay open for copy and pasting.  I can try moving it a little more so its easier to move you mouse and keep it open, but other than that I think at this point we've gotten enough blood from this stone 😉

**Comment by reza1615** [comment]
![image](https://user-images.githubusercontent.com/2202483/78208987-d4e41580-7473-11ea-9a7b-1458502f207d.png)

**Comment by aschonfeld** [comment]
Something has to be up with the browser you're using because mine opens up directly below:
![image](https://user-images.githubusercontent.com/11547371/78248755-37143900-74bb-11ea-9f46-7a187244ecf1.png)

I can try making it open directly above the initial code snippet rather than below, but I don't know what is forcing your to the left like that.
