### ISSUE TITLE
Resize doesn't work

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#132]
Resize doesn't work
![image](https://user-images.githubusercontent.com/2202483/77840300-e7004400-7153-11ea-975d-241f4114e529.png)

**Comment by aschonfeld** [comment]
The resize button is strictly there for fixing when column widths get out of sync and cell values are wrapping.  This shouldn't happen, but if it ever does I think this will fix it.

Maybe I should look into renaming that button to something else because "Resize" can mean something totally different.  Maybe "recalculate column widths" although that would need some small font in order to fit.

**Comment by reza1615** [comment]
for icon may be | |
for name "Auto col. width"
or "Refresh width"

**Comment by aschonfeld** [comment]
How about this: 
![image](https://user-images.githubusercontent.com/11547371/77942221-4d3ab300-7289-11ea-9c95-5fa3413d4198.png)
