### ISSUE TITLE
Chart's export code doesn't show the mathplotlib commands

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#135]
Chart's **Code Export** doesn't show the matplotlib commands or plot commands.

![image](https://user-images.githubusercontent.com/2202483/77842247-216ede80-715e-11ea-910d-5b5520bcd11a.png)

**Comment by aschonfeld** [comment]
added in v1.10.0

**Comment by bhaskoro-muthohar** [comment]
Hi, it's still missing on Describe Code Export

![image](https://user-images.githubusercontent.com/35159954/109392789-a3f4b500-7950-11eb-817a-3238e8023444.png)

**Comment by aschonfeld** [comment]
@bhaskoro-muthohar I didn't add code to generate matplotlib charts, but I did add code to generate  plotly charts.  D-Tale primarily deals in plotly charts since that is what is used for the "Charts" page.  Hopefully this works for you.  Here is a demo:

https://user-images.githubusercontent.com/11547371/111408515-c6eecb00-86ab-11eb-8143-52c1f29a85fb.mov

I am in the process of releasing version 1.40.0 of the code that will include these changes, should be out within the next hour.
