### ISSUE TITLE
Chart Map: SccaterGeo UI

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#143]
* Projection dropdown window's width needs to be wider
![image](https://user-images.githubusercontent.com/2202483/78291729-e79e2f00-74f3-11ea-906b-93b1d9dd1aae.png)

* I extracted projections' svg. when user select one of them, in a picture box the image can be shown to help the user for selection the proper one.
[Projections.zip](https://github.com/man-group/dtale/files/4423464/Projections.zip)
![image](https://user-images.githubusercontent.com/2202483/78298752-ef180500-7500-11ea-8bec-f5c79e7a8e68.png)

* For SccaterGeo: It should accept empty Value (Just show some pins on the locations without any value)

**Comment by aschonfeld** [comment]
Good suggestions

**Comment by aschonfeld** [comment]
I tried adding the projection samples to the app but the files were huge.  So the best solution I could come up with was hosting this markdown file with links to all the svgs: https://github.com/aschonfeld/dtale-media/blob/master/projections_listing.md

Then I included an info link in the Projections label: 
![image](https://user-images.githubusercontent.com/11547371/78363689-34cce000-758a-11ea-80c2-34ceeaca275c.png)

I couldn't have links directly to the svg files themselves because of the cross-scripting problems and I tried loading the files from the back-end but that fell over because of proxy problems and I really didn't want to support proxy settings for something so small.

**Comment by reza1615** [comment]
I made them smaller (hight, size). please test them
[Projections2.zip](https://github.com/man-group/dtale/files/4427447/Projections2.zip)

**Comment by aschonfeld** [comment]
That is much better (.348 mb) but it would still make up about 5% of the egg if I include them as static files.  If you think these thumbnails would be a big win I'll add them, but I would think the simple markdown I setup on github should be more than enough of a sample for users.

**Comment by reza1615** [comment]
1- In my opinion make the code more visual is more attractive 
2-As you mention before we should reduce using internet
3-For each case going to help is annoying.

**Comment by aschonfeld** [comment]
One last piece to make note of is that the demo site I'm running right now on PythonAnywhere only has 512MB of space so every file we add to this makes a big difference.  I'm trying to see if I can get someone to flip the bill on getting more space but as of right now those are the constraints.

**Comment by reza1615** [comment]
I made the gray-scale and reduce their size now total size is 136 K
[Projections3.zip](https://github.com/man-group/dtale/files/4427750/Projections3.zip)

**Comment by aschonfeld** [comment]
Ok, I'll integrate this and I'm close to getting my employers to get us some more space on PythonAnywhere :)

**Comment by aschonfeld** [comment]
One last issue, that extra space to the right of 'Projection' no longer exists since I've added grouping to maps as well.  So the best I'll be able to do it is to continue with that '?' icon in the label that you can hover over once you've selected a value to view its thumbnail.

The best scenario would have been to embed the images into the dropdown options, but it looks like dash support that even though the component they are using "react-select" does actually support it.

**Comment by reza1615** [comment]
https://github.com/plotly/dash-colorscales/blob/master/README.md

**Comment by aschonfeld** [comment]
added v1.8.3
