### ISSUE TITLE
heat map

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#156]
![image](https://user-images.githubusercontent.com/2202483/78502695-5667cc00-7730-11ea-8ae1-5a0ebc9de5ad.png)
Heat Map calculates color range based on each columns. In my opinion before applying colors it should ask in a popup window 
"Do you want to render heat map based on :
* based on each columns?
* whole columns?"
This ambiguity cause when we have PIVOT table and all columns have the same unit (for this example all of them are years and values are price)
Now cell A, B, C for whole color range should have different back color.

**Comment by reza1615** [comment]
Why heat map doesn't accept int?

**Comment by aschonfeld** [comment]
Sorry, I meant to come back to this exact problem (columns all on the same basis) with the heat map when I first built it and got sidetracked.  I'll also look at the issue with the integers.

**Comment by aschonfeld** [comment]
So I've added ints (I think I originally blocked them because out security ids were integers and it seemed weird to use them in a heatmap) and here's how I structured choosing "All Columns" vs. "Each Column"
![image](https://user-images.githubusercontent.com/11547371/78519062-1d5f4400-7790-11ea-927f-d20c5552da54.png)

Most columns are red because they are getting skewed by the large integers in the "id" column, but I'm just using your DemoData3 data here so if you have a PIVOT example you want me to shoot over a screenshot of, more than happy to oblige :)

**Comment by reza1615** [comment]
http://desktop-o55c2t7:40000/dtale/main/2

Pivot
Row= State
Column = Yr_bulit
Value = Price
agg = Mean

**Comment by reza1615** [comment]
Can you add some check box on the columns to exclude come columns?
or open a window with all nominated columns and user can exclude or add them

**Comment by aschonfeld** [comment]
What i can do is have it take into account columns you’ve hidden and ignore them from the calculation.

One thing to note is that i dont take into account any filters, which in most cases is a actually a good thing, because its very computationally expensive to maintain that information.  But if you think its a big win I can try updating that.

**Comment by reza1615** [comment]
We have to types
* by column which we don't have any problem also for ids 
* whole:
for this type we can calculate mean of each column and exclude the outliers.
for exmple
col1 mean =1315154625566
col2 mean =563
col3 mean 123
col4  mean = 1233

so col1 should be excluded
for outliers I wrote a simple code in #137

**Comment by aschonfeld** [comment]
So I've got a change for the hidden columns ready to roll, but the outliers logic will be a little tougher since the computation to figure out the overall min/max is being done on the client side.

**Comment by aschonfeld** [comment]
v1.8.7
