### ISSUE TITLE
Close D-Tale and push back the dataFrame to a variable (get_df)

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#177]
Is it possible after shutdown, D-tale  push back the table as a dataframe to a variable?
for example
```
import dtale
import pandas as pd
df = pd.DataFrame([dict(a=1,b=2,c=3)])
d = dtale.show(df)
```
After opening D-tale, doing some edits on the data and shutdown or close D-tale
`new_df= d.get_df()`

**Comment by reza1615** [comment]
to make it easy. when user press shutdown stale export csv. when get_df() run. open the temp csv

**Comment by aschonfeld** [comment]
I'm going to close this issue since users now have access to an "Export" function which can export data to CSV or TSV files.  Also at anytime during your D-Tale session you would like to obtain the current dataframe that D-Tale is working on you can use the `.data` property on your D-Tale instance.  For example:
```
d = dtale.show(df)
my_dtale_data = d.data
```

**Comment by reza1615** [comment]
please add .data functionality to the documentation

**Comment by aschonfeld** [comment]
It actually is in the documentation [here](https://github.com/man-group/dtale#additional-functions-available-programmatically) but maybe you could find a better spot for it
