### ISSUE TITLE
Percentage Sum and Percentage Count + BarSort

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#189]
After applying  BarSort became wrong.

Before
![image](https://user-images.githubusercontent.com/2202483/80314951-b1865f00-87c2-11ea-9e38-6be232670f0d.png)
After
![image](https://user-images.githubusercontent.com/2202483/80314907-74ba6800-87c2-11ea-8866-9359833b7940.png)

**Comment by aschonfeld** [comment]
Honestly, I think in this case "Barsort" shouldn't be available because it won't know what to sort on because of the fact that each bar consists of multiple groups.  The only option would be to sort on the total "Percentage Sum" which in this case is 100 for everything and then the sorting is random.

I think my suggestion is to hide the "Barsort" dropdown when users choose "Percentage Sum" or "Percentage Count" aggregations.

The only other option would be allow user to sort the data based on individual groups, which would be far too much work for so little value.

**Comment by reza1615** [comment]
I am agree. hide the "Barsort" for these aggregations

**Comment by aschonfeld** [comment]
fixed v1.8.11
