### ISSUE TITLE
DataFrame with DatetimeIndex is shown as RangeIndex

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#196]
When I try to show a DataFrame that has an index of type DatetimeIndex, in dtale it is shown as a RangeIndex.

It would be very useful to display that DatetimeIndex.

Sample code:

```
import pandas as pd
import pandas._testing as tm

df = tm.makeTimeDataFrame()
```

```
df
```
![Capto_Capture 2020-05-03_05-03-28_p  m](https://user-images.githubusercontent.com/4047415/80917570-13653c80-8d60-11ea-8c0a-ffd89dfdf03d.png)

```
from dtale import show

show(df)
```
![Capto_Capture 2020-05-03_05-03-46_p  m](https://user-images.githubusercontent.com/4047415/80917573-19f3b400-8d60-11ea-9f3c-ef09416c19a8.png)

**Comment by aschonfeld** [comment]
So in order to get this to work correctly you would have to updated your code to this:
```
import dtale
import pandas._testing as tm

df = tm.makeTimeDataFrame()
df.index.name = 'date_index'
dtale.show(df)
```

The problem is that on startup it doesn't maintain indexes because it would be too hard to keep track of. So it runs `.reset_index()` on any startup and drops any columns names `index` by default.  Because in most instances users are giving dataframes with index names and it will the resulting columns after the `reset_index()` call will be pre-locked on the grid (to show the users they were the original index).

The best option I can offer other than the code fix above is that I can check to see if the index on the dataframe is not `dtype('int64')` (which is the default 0 to n-1 natural index in pandas) and if it isn't then I will allow the default naming convention of "index" to pass through for those.

But the best solution is to just include a name on any index column that isn't "index".

Hope this helps!

**Comment by juanfcocontreras** [comment]
> The best option I can offer other than the code fix above is that I can check to see if the index on the dataframe is not `dtype('int64')` (which is the default 0 to n-1 natural index in pandas) and if it isn't then I will allow the default naming convention of "index" to pass through for those.

I think that alternative would be great, but while this workaround is enough for me.

Thank you very much!

**Comment by juanfcocontreras** [comment]
I think it would be better to do the following check instead of `df.index.dtype == "int64"`. This way you could have a custom RangeIndex and it would be kept.

```
df.index.equals(pd.RangeIndex(0, len(df))) == True
```

**Comment by aschonfeld** [comment]
Added v1.8.12
