### ISSUE TITLE
Dealing with empty cell and nan

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#238]
Now when I open the below code in the D-tale. it changes the empty cell to nan. I couldn't find effective way to replace nan and NaN and np.nan with empty cell.
In my opinion it is good enhancement to replace automatically all these missing with np.nan or another customize option.
``` python
import pandas as pd
import numpy as np
data={'col1': [1, 2,'',3,'nan',5,6,7], 'col2': [1, 2,'',3,'',np.nan,'',7], 'col3': ['', 2,'',3,'','NAN','',7]}
df=pd.DataFrame(data)
```
![image](https://user-images.githubusercontent.com/2202483/89729491-46c10280-da04-11ea-8070-5bca97406bf5.png)
D-tale shows the below
![image](https://user-images.githubusercontent.com/2202483/89729498-550f1e80-da04-11ea-8c89-c20d1a850a4d.png)

Also in the description, it shows some of them as **nan** and some of them as **null** but doesn't count them as missing 
![image](https://user-images.githubusercontent.com/2202483/89729580-247bb480-da05-11ea-937a-c751a4a8cde4.png)

**Comment by aschonfeld** [comment]
@reza1615 I don't know of a good way to handle your string nans (ex: 'nan', 'NAN') other than suggesting using your "Replacements" option and replace those strings with actual `np.nan` values.

Once you've done that they will be counted as missing.  But also the latest round of "Type Conversion" enhancements should allow you to update these columns to floats at which point these strings will be considered `np.nan`.

That being said I am working on a way to allow users the ability to change what `np.nan` is represented as in the UI (the default is 'nan').  Here's a demo of what I have: https://youtu.be/I3qYHexY214

So I am going to close this case since I already have a case for this `np.nan` formatting functionality.
