### ISSUE TITLE
Running dtale in Docker (CLI mode), binding host to 0.0.0.0

### ISSUE THREAD

**Issue by AshirBorah** [man-group/dtale#249]
First of all, great job on this package/app

I am trying to use dtale in a docker container and have got most of it set up but the links are a little different than what I usually see for example http://85c1e783744c:40000

These are not available to my system browser even after exposing the port. From my initial searching, it looks like I can get around this by passing 0.0.0.0 to flash as the host to use. What would be the easier way to achieve this?

**Comment by aschonfeld** [comment]
So D-Tale is hardcoded to point Flask at hostname `0.0.0.0`.  The issue here is the logic I have to try and find the hostname to be used for links.  That hostname looks like maybe the process id that is associated with your docker container.

If you know what your host should be then you can pass that as an argument to `dtale.show`.  Here's an example:
`dtale.show(df, host='xxxx') # should create a link of http://xxxx:40000`

That's interesting that exposing the port did not solve this though.  I feel like I hit this issue early on when I was developing using docker.  Did you try adding the `--network host` when calling `docker run`?  Similar to what I'm doing [here](https://github.com/man-group/dtale#docker-development)

**Comment by AshirBorah** [comment]
The network host solved it! Thanks
