### ISSUE TITLE
how to run project locally ( local environment )

### ISSUE THREAD

**Issue by ecakashjadhav** [man-group/dtale#250]
hello. I'm a beginner in the flask. how to run app in the local environment. without docker, because I use command "python app.py" to run but command not shows any error and exit. please suggest me to run the app.

**Comment by aschonfeld** [comment]
Hi, sorry I should probably add some documentation on doing this.  Here's an example script:
```
import pandas as pd
import dtale

if __name__ == '___main__':
    df = pd.DataFrame([1,2,3,4,5])
    dtale.show(df, subprocess=False)
```

So if you copy that code into a python module named whatever you want you should be able to run it like you asked: `> python [your filename].py`

Good luck

**Comment by aschonfeld** [comment]
Sorry, the magic that I added to that code snippet is the `subprocess` flag.  Without that set to `False` it will run D-Tale as a subprocess (which is what is needed in order to run it in a notebook or console and still get access back to your console or notebook) which will then terminate when the script terminates.  Which is immediately :)

**Comment by ecakashjadhav** [comment]
can I run cloned d-tail repo run locally with the environment?. Because I try to run using "dtail/dtail#python app.py" after that command server not start and command not showing any output.
please tell me If any changes or suggestions.

**Comment by ecakashjadhav** [comment]
> Hi, sorry I should probably add some documentation on doing this. Here's an example script:
> 
> ```
> import pandas as pd
> import dtale
> 
> if __name__ == '___main__':
>     df = pd.DataFrame([1,2,3,4,5])
>     dtale.show(df, subprocess=False)
> ```
> 
> So if you copy that code into a python module named whatever you want you should be able to run it like you asked: `> python [your filename].py`
> 
> Good luck

when I run in console not showing any output

**Comment by aschonfeld** [comment]
There was no output produced when you ran that code?  That seems very odd to me.  I would at least expect a URL to be printed to the console which can be pasted into you browser to start working with D-Tale.

Also, you may have already done this but don't include the `>` in you command.  That was only there to signify a command-line.

As for your comment about running app.py form your cloned repo, that won't work because D-Tale is not actually a standalone web application but an on-demand web application.  So it gets instantiated through code `dtale.show(...)` and not from a startup script. That being said, my code snippet I sent is an example of how to turn it into a standalone app.

There is an option to run it from the command line right now:
* you must run `python setup.py develop` on your cloned repo
* then you can  on of the CLI loaders, for example: `dtale --csv-path my_data.csv`
  * this will load a CSV into D-Tale (here's more information on the [CLI options](https://github.com/man-group/dtale#command-line))
  * it also gives a nice in-depth example of setting up [custom CLI loaders](https://github.com/man-group/dtale#custom-command-line-loaders)

**Comment by ecakashjadhav** [comment]
'python setup.py develop' After that 'dtale --open-browser' command shows error
![Screenshot from 2020-08-18 23-54-01](https://user-images.githubusercontent.com/68955835/90551059-6b5c6d80-e1ae-11ea-9293-9a60a0d8135f.png)

**Comment by aschonfeld** [comment]
Makes sense since you didn't load any data.  D-Tale requires the loading of data.   I'm planning on adjusting that requirement now that I've added the ability to load CSV files.

Anyways, I think now that I see that you code is working you can revisit the original code snippet I sent and try adding `open_browser=True` to it if you want the browser to open automatically.  So for example:
```
import pandas as pd
import dtale

if __name__ == '___main__':
    df = pd.DataFrame([1,2,3,4,5])
    dtale.show(df, subprocess=False, open_browser=True)
```
I would think this code will work now, assuming you still have the virtual environment (env_dtale_3.8) activated when you run the code.

**Comment by ecakashjadhav** [comment]
It works. Thanks. 
one more question how to debug code in dtale?

**Comment by aschonfeld** [comment]
Ok, that's great.  As for the debugging question it's your personal preference but there's a couple options I have used over the years:

1. *PDB* - you can use pdb by adding this line of code anywhere in your codebase `import pdb;pdb.set_trace()` and it will halt your program at that point and you step through it line by line using CLI interface.  Here's more [documentation](https://docs.python.org/3/library/pdb.html)

2. *IDE debuggers* - this is what I generally use.  Currently I'm using PyCharm and you can simply click on a line of code which will insert a breakpoint (similar to pdb but without having litter your code) and then you click the "Debug" button next to the "Run" button and it will halt your code at that breakdown and allow you to step through it using the GUI rather than a clunky CLI.

If you go the IDE route I can help you setting up a run configuration.  As for this case I'm going to close it since you're able to get it running but feel free to keep asking questions here about setup.
