### ISSUE TITLE
how to save changes in showed data file in browser

### ISSUE THREAD

**Issue by ecakashjadhav** [man-group/dtale#277]
I'm edited column value in the browser. how to save changes or any option to do that. because I want to save user changes value in CSV.

**Comment by reza1615** [comment]
@ecakashjadhav you mean diff values or the final result. for example
1
2
3
changed to
1.5
2
3
do you want to see
1 > 1.5
or
1.5
2
3

**Comment by ecakashjadhav** [comment]
yes and I want to save these changes in the original datafile CSV

**Comment by aschonfeld** [comment]
So, in addition to being able to upload a CSV to a running instance of D-Tale you can also export your data to a CSV or TSV file.  Simply click the button in the upper lefthand corner for the main menu and click the "Export" button listed 5th from the bottom (4th in this case since I turned off the "Shutdown" button)
![image](https://user-images.githubusercontent.com/11547371/95203113-4a78c780-07b0-11eb-9b35-922ef1077607.png)


Hope this helps! 🤞 

FYI: I plan on adding the ability to kick off D-Tale without specifying an initial dataframe and that way you can start up D-Tale and load CSV to your browser and not have to worry about needing an initial dataframe upon startup.

**Comment by aschonfeld** [comment]
The ability to load D-Tale without data specified `dtale.show()` is now available.  I'm going to close this issue.
