### ISSUE TITLE
Updates/workarounds for a few dependency issues

### ISSUE THREAD

**Issue by phillipdupuis** [man-group/dtale#284]
Hi, finally getting back around to working on this :)

You don't need to worry about this one, I already have the PR mostly done and will submit it within the next couple days - it's just a few weird dependency issues.

1. dash requirement will need to be bumped - currently it's >=1.5.0, but with 1.8.0 [these drilldown tests](https://github.com/man-group/dtale/blob/55a9cf01f9f449b4e8d43f193f0b5c788e15ab42/tests/dtale/dash/test_drilldown.py) fail because the payload returned from `"/charts/_dash-update-component"` doesn't have the expected shape. I'll figure out exactly what release they made that change in
2. [test_show_loaders.py](https://github.com/man-group/dtale/blob/master/tests/dtale/test_show_loaders.py) uses `mock_show.call_args.kwargs` a bunch, [which is only available in mock>=3.0](https://github.com/testing-cabal/mock/commit/19b90359e941a86423f852e50731edea9a086974). Easiest solution is to replace it with `mock_show.call_args[1]` since it's the same thing, but alternatively could also have tests require mock>=3.0
3. there is no pandas version requirement (which is great) BUT [this code](https://github.com/man-group/dtale/blob/master/dtale/views.py#L1564) can cause errors if your version is <1.0 and you've got a string column, since `pd.api.types.infer_dtype` will return "string" but the string dtype wasn't added until 1.0.

For #3 I was thinking it could do something like this:
```python
try:
    uniq_grp["value"] = uniq_grp["value"].astype(uniq_type)
except TypeError:
    pass  # keep values as is
```
But I'm not sure if that's ideal? Lemme know if you think something else would be better

**Comment by aschonfeld** [comment]
Doopes, good to hear from you brah!  I'm thinking I haven't hit on these dependency issues locally because I haven't refreshed my environment too often.  But it still is a little weird because the CircleCI builds don't fail and they use the most [up-to-date versions](https://circleci.com/api/v1.1/project/github/man-group/dtale/2246/output/106/0?file=true&allocation-id=5f8131b5d625c0357d56cf97-0-build%2F2D2F84EE).

1) When I look at the current CircleCI builds they are using dash 1.16.3 and that test seems to work fine.  We can try bumping it to higher version tho, its been long enough.
2) This change seems totally fine to me
3) This seems fine to me, I'd say just try testing the "Describe" popup with some string data if that is the type that's causing the issue because that is where this code is used the most

Side note, did you see this [comment](https://github.com/man-group/dtale/issues/276#issuecomment-705945289)?  Its in regard to your "shelf" stuff

**Comment by phillipdupuis** [comment]
Haha same, miss having you around! Hoping the pitt is litt

For #1, I was unclear - bumped the version up to 1.16.0 and it works great, but with 1.8.0 it didn't work even though the requirement is >=1.5.0.  So the real requirement is somewhere between 1.8.0 and 1.16.0, I just need to find roughly where. Should be easy

And I did not, thank you! I actually have wanted to get back to that a bit, especially the redis store - think I can make it a bit more useful

**Comment by aschonfeld** [comment]
@phillipdupuis thanks man, good to have your input on this package again!  There have definitely been some people asking about your `global_state` work.  Feel free to hit me on my email directly anytime

**Comment by aschonfeld** [comment]
@phillipdupuis hey man is this still an issue?  If not I'm going to close it.  Thanks

**Comment by phillipdupuis** [comment]
> @phillipdupuis hey man is this still an issue? If not I'm going to close it. Thanks

I do not believe so, nope! So I'll jump ahead of you and close it

If/when I hit errors like this again I'll report them :)

**Comment by aschonfeld** [comment]
@phillipdupuis thank you good sir
