### ISSUE TITLE
filter outliers and histogram 

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#303]
Apply filter outlier doesn't work for column description  > histogram
i.e. try it for price column because of outliers the rest of data in histogram is vanished 

![image](https://user-images.githubusercontent.com/2202483/96338434-1cbb3a80-105c-11eb-81a0-017daa656f97.png)

**Comment by aschonfeld** [comment]
Is this on the demo site?  If it is thats the reason this doesn't work sometimes.  Once again, because of the fact they spawn multiple instances of the app and you can't control which instance your requests will be sent to.  Going forward, please keep that in mind when validating functionality using the demo.  The bugs i'm more concerned about are ones involving using the app in a localized setting.

I was able to verify that this works locally.
