### ISSUE TITLE
D-Tale Charts

### ISSUE THREAD

**Issue by vijaydewan** [man-group/dtale#311]
It looks like trendlines do not work when exporting charts to html.  Is there a way to put a trendline into an exported chart?

Also, I noticed that the plotly "export to png" function was removed in version 1.7.6.  Is it possible to manually put this back in?

Thanks for your help.

**Comment by aschonfeld** [comment]
Just wanted to give you an update on this.  I'll be adding fixes for both of these in the next release.  The only catch about the PNG export fix is that it requires a dependency on the package `kaleido`

**Comment by vijaydewan** [comment]
Thanks Andrew!

**Comment by aschonfeld** [comment]
Fixed in v1.20.0.  Additional info on this, in order to use the "Export to PNG" please install `kaleido` & upgrade `plotly` to at least 4.9.0 (both of which should happen automatically if you're installing with `pip`).  

If you're installing with `conda` then you'll have to install `kaleido` using the following command: `conda install -c plotly python-kaleido`
