### ISSUE TITLE
Unique words in the column description

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#339]
Unique Values section just shows Value count. when the tab changed to the word count it should show unique words
![image](https://user-images.githubusercontent.com/2202483/101919031-1ba81480-3b98-11eb-8bbc-9fa15ad6f90f.png)

**Comment by aschonfeld** [comment]
I don't think I understand what you're asking for here. Since `City` has underscores in it each value is considered one word so that means the "Word Value Counts" & "Value Counts" will be the same, which is correct.

**Comment by reza1615** [comment]
![Screenshot_20201212-131121_Chrome](https://user-images.githubusercontent.com/2202483/101991566-9433d180-3c7b-11eb-91fb-a534b61bcd6a.jpg)

**Comment by reza1615** [comment]
In above screenshot west, de ,...
are not in the below list.
In my opinion the words in the chart and list should be smilare 
now the list just shows value counts it should show words when the chart is word

**Comment by aschonfeld** [comment]
So the problem here is that "Word Value Counts" is a separate operation from the one that loads "Unique Values" (Unique Raw Values, no splitting applied) because it is very resource heavy.  I can try seeing if I can pull the information from the chart, but most likely it will be a while until this is fixed.
