### ISSUE TITLE
where is groups

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#404]
I wanted to make a chart for COVID sample data but I couldn't find them groups input box
![Screenshot from 2021-01-25 15-12-20](https://user-images.githubusercontent.com/2202483/105760497-e2e1b600-5f1f-11eb-9d91-0b62844407f2.png)

**Comment by reza1615** [comment]
If group:
For example in the building csv 
* Integer > it will show groups + group type bins (This is ok)

Wrong with the below
* Float > doesn't show group type (bin).  group ==lat   > should have option for value and bin
* String > doesn't show groups.  group ==Country       > should have option for value
* Date >  doeasnt Show group type (bin) . group = DateAdded (weekly) > should have option for value and bin

**Comment by aschonfeld** [comment]
Fixed in v1.32.1

**Comment by reza1615** [comment]
Thank you for the changes. now it is diapered for float
![Screenshot from 2021-01-26 11-40-41](https://user-images.githubusercontent.com/2202483/105875206-83d97b00-5fcb-11eb-9497-c47d2dfea0ca.png)

**Comment by aschonfeld** [comment]
I have a fix for this, but as for the different date breakdowns there are only a couple where "Binning" makes sense becuase all the others are returning date objects.  Those types are Hour & Weekday, but honestly I wouldn't really want to bin those because there isn't that many values for each.
* Hour has 24 values, 0-23
* Weekday has 7, 0-6
So binning doesn't really make sense since the charting functionality allows for selecting up to 30 group values which this falls well below that threshold
