### ISSUE TITLE
Save output to a re-useable html file

### ISSUE THREAD

**Issue by eafpres** [man-group/dtale#439]
I'm trying to get the output to an html file. I tried saving from the browser but that didn't save the data.

code:
```
data = pd.read_csv(fn + '.csv')
dtale.show(data)
```

**Comment by aschonfeld** [comment]
So you are looking to dump the contents of your grid from D-Tale into an .html file?  Currently you can export to CSV or TSV from the main menu:
![image](https://user-images.githubusercontent.com/11547371/108565288-6b126b80-72d2-11eb-95dc-6fea55b7676d.png)

**Comment by eafpres** [comment]
> dump the contents of your grid from D-Tale into an .html file

Actually a bit more than than; some other explore / viz modules can generate the html, which I can share, view later, etc.  I want to maintain the interactvity of the entire output that is displayed in the browser.

**Comment by aschonfeld** [comment]
I get what you're saying now.  Unfortunately, since the data is loaded server side to the client this is impossible.  If loaded all of the data to the client (which if you were dealing with a lot would easily crash) and performed all our operations client-side then you could definitely do this.

Maybe a client-side snapshot could be something added down the road which would only store what data you are currently viewing, but even that would be a big undertaking since the majority of our functionality is based off leveraging pandas on the server-side.

**Comment by aschonfeld** [comment]
We do offer the re-usable chart functionality provided from dash, but ultimately thats not the grid :(

**Comment by eafpres** [comment]
Thanks for the clarification.  Your architecture is good so as to not crash the browser etc.  It's a very slick output, BTW.

**Comment by aschonfeld** [comment]
@eafpres Thanks, feel free to toss your ⭐ of approval on the repo and bring any other requests you can think of!
