### ISSUE TITLE
Handling periods and spaces in column names.

### ISSUE THREAD

**Issue by EpochalEngineer** [man-group/dtale#452]
Trying to explore a google forms response spreadsheet with quesitons having periods and lots of spaces. It seems two kinds of errors occur which can be shown with this simple dataset:

pd.DataFrame(([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['A1. asdf', 'b '*50, "c"])

Columns with periods are not clickable, and can't access the column menu.

Columns with spaces are clickable, but above a certain length sorting does not work. Sometimes I can see this error in the console:

`  File "/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b'
`
dtale==1.37.1
pandas==1.1.5
Python 3.8.5

**Comment by aschonfeld** [comment]
@EpochalEngineer thanks for all the detail!

1) I'm looking into why the column header is not displaying the entire width of the header text.
2) The issue with the periods within column names is that the period gets included in the CSS class name which breaks some CSS selectors. I'm updating the JS to add a `name` property that can be used in the selector cleanly.
3) As of the `KeyError` the problem is with the fact that the column name has trailing whitespace but when it tries to grab it from the dataframe it is not including that whitespace so its saying it doesn't exist.  I'm going to add some additional formatting when calling `dtale.show` which will strip any leading/trailing whitespace so we can avoid this.

I was going to do a release but I'll wait until these issues are fixed and can be included

**Comment by EpochalEngineer** [comment]
Sounds good, thanks!

Would it also be possible to add resizing of columns and word wrap?

**Comment by aschonfeld** [comment]
I managed to get a fix for (1)  as well.  As for resizing & word wrap I'll probably split those out into another release since they will be fairly more complex.

**Comment by aschonfeld** [comment]
@EpochalEngineer just released v1.38.0 which handles the 3 issues you came across.  I'll work on resizing & word wrapping soon.  Please let me know if you have any ideas on how this will work?  I have formatting options based on the data type of each column, but I could add some more data type-agnostic options as well.  Lastly, feel free to toss your ⭐ on the repo.

Let me know if you experience any other issues, thanks again for the feedback.

**Comment by aschonfeld** [comment]
@EpochalEngineer here's a demo of resizable columns!

https://user-images.githubusercontent.com/11547371/111001395-b4922b80-8351-11eb-9ef5-3a8c1ae9dbea.mov
