### ISSUE TITLE
correlation shows label 'index' is not unique  error

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#487]
my index has unique data but it shows the below error. 
In my opinion, if the index has duplicated still it should force to show the unique

![image](https://user-images.githubusercontent.com/2202483/119003243-918c8500-b95b-11eb-82ba-cd385966cdbc.png)

**Comment by aschonfeld** [comment]
@reza1615 can you give me some more information about the structure of your data?
* is this timeseries data?
* or is this a correlation of two columns as a whole?

**Comment by reza1615** [comment]
1-it is tubular data for binary classification like housing data
2-yes it is correlation of two columns as whole and it shows for all columns

**Comment by reza1615** [comment]
I figured out when I delete the index it will resolved.
In my opinion on fly you can run the below snippet before running the correlation code.
df.index = range(len(df))

**Comment by aschonfeld** [comment]
So the issue was that when I was calculating the scatter I created a temporary column called `index` and so if there was an additional column named `index` being used in the correlation then that would cause our sorting issue with non-unique column names.

I have since updated the code to use `_scatter_index` (which still may cause a non-unique issue if there is a column of that name) which should be far less commonly used.

**Comment by aschonfeld** [comment]
fixed in v1.48.0
