### ISSUE TITLE
AttributeError: module 'dtale' has no attribute 'auth'

### ISSUE THREAD

**Issue by SundarakumarK** [man-group/dtale#516]
Hi All,

I get this error when i try to import dtale. Can someone please help guide me on how this can be tackled?

**Comment by aschonfeld** [comment]
I'm on the latest version of D-Tale (1.49.0) and I have no come across this issue.  If you're running a virtual environment then try running the following:
```
pip uninstall dtale
pip install -U dtale
```

If that doesn't work can you send me the full stacktrace of the exception?  Or is the AttributeError the full stacktrace?  Also, can you send me how you're invoking `dtale.show`?  You don't have to tell me anything about the data you're feeding to it just how you're invoking it.

Lastly, in order to use the `auth` package you need to activate it using the global configuration file or using `dtale.global_state` (documentation is [here](https://github.com/man-group/dtale#authentication)).  Are you using any of that?

Apologies for the inconvenience.

**Comment by SundarakumarK** [comment]
Hi, 

Thank you for the reply. 

I tried uninstall and reinstalling the updated version, no luck. 

Here is the full error

import dtale
Traceback (most recent call last):

  File "<ipython-input-150-33560840fdc5>", line 1, in <module>
    import dtale

  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\__init__.py", line 6, in <module>
    from dtale.app import show, get_instance, instances, offline_chart  # isort:skip

  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\app.py", line 25, in <module>
    import dtale.auth as auth

AttributeError: module 'dtale' has no attribute 'auth'


I am working on a secured system, not sure if I can change the settings for auth. 

Thanks again.

-Sundar

**Comment by aschonfeld** [comment]
Ahhh, so you're using anaconda. Could you try the following:

```
conda remove dtale
pip uninstall dtale # just in case the pip installation is still lying around
conda install dtale -c conda-forge
```

If that still fails then I would try removing the package directly `rm -r C:\ProgramData\Anaconda3\lib\site-packages\dtale`

Hope this helps.  I know that conda sometimes has problems with installing software sometimes which is why I prefer managing my own virtual environment using pyenv + pip

**Comment by SundarakumarK** [comment]
Thanks a ton !

Awesome Library :) 

Kudos. 

-Sundar

**Comment by aschonfeld** [comment]
@SundarakumarK no problem! Please toss your ⭐️ on the repo if you havent done so already 🙏
