### ISSUE TITLE
Dtale Output Not being rendered on Jupyter Notebook 

### ISSUE THREAD

**Issue by sayedathar11** [man-group/dtale#546]
Hello this is related to https://github.com/man-group/dtale/issues/542

I have installed new version of Dtale and the error which was occuring due to datatypes have also being address I guess but the output of the dtale.show() , is not being rendered .  I also waited 8 - 12 hours for output to render but its not being rendered .

I also try opening the same on using 
`d = dtale.show(data, ignore_duplicate=True)
d.open_browser()`

Still Output is not being rendered , not that my dataset is having  1.6 millions rows and 26 columns , 
Can you please add functionality that can render this dataset properly .

I am also attaching screenshot below 
![dtale_error3_v2](https://user-images.githubusercontent.com/17905011/127637266-3af6006a-87cc-4efa-8bba-76379ec0cf0c.PNG)

**Comment by aschonfeld** [comment]
So this might be an issue with how much memory your machine has, since I am able to load 1.6 million rows with 31 columns in jupyterhub with no issue:

https://user-images.githubusercontent.com/11547371/127649333-5cf85971-5590-413d-bd13-363c05f50d1d.mov

One thing you can do to optimize memory consumption is to use the `drop_index` parameter.  For example:

`dtale.show(df, drop_index=True)`

Last thing, I've never actually tried using `open_browser` from within a jupyter notebook before but I couldn't get it working.

**Comment by aschonfeld** [comment]
I figured out the issue with the `open_browser`.  So the problem is that when using `JUPYTER_SERVER_PROXY = True` it will no longer include the hostname & port in the URL.  There is no way that I can tell you can figure out the hostname & port that jupyterhub is running on programmatically.

When setting `JUPYTER_SERVER_PROXY` to `False` it will revert back to the original format where it is not attaching the D-Tale process to the notebook and thus includes the hostname & port in the URL which will allow `open_browser` to work as expected.

I can do some digging on how to expose the hostname & port of the notebook but theres no guarantee I can figure that out.  So when using `JUPYTER_SERVER_PROXY = True` I'd either do one of two things:
* render D-Tale directly in your notebook then click "Open In New Tab" from the main menu
* print the value of `d._main_url` and then paste it into a separate tab with the hostname & port included in front of it

**Comment by sayedathar11** [comment]
Ok @aschonfeld  Thanks alot .
