### ISSUE TITLE
Concern about generate a link that can share with others

### ISSUE THREAD

**Issue by perryisbusy** [man-group/dtale#556]
Hello,

Just wondering that is it possible to generate a link(HTML) like pandas_profiling that can share with others. The link can be opened from any system without opening Jupyter Notebook again. Thanks!

**Comment by aschonfeld** [comment]
So this is possible, but the original notebook that was running your D-Tale instance must be up and running in order for others to use the link.  You can figure out your D-Tale link by running the following in your notebook:
```
import dtale
import pandas as pd

d = dtale.show(pd.DataFrame([1,2,3,4,5]))
print(d._main_url)
```

It should print something like `http://[host]:[port]/dtale/main/1`

If you are running with `JUPYTER_SERVER_PROXY = True` then the url won't have the host & port on it so you'll have to copy & paste the hostname & port of your notebook to the front it before sending it to others.

Once you close down your notebook the links will no longer work because D-Tale is a running Flask application under the hood.

D-Tale's chart builder does offer offline charts which you can send around to others.  These can be generated by clicking the following link after building your chart:

![image](https://user-images.githubusercontent.com/11547371/130356242-dbb81cf7-3815-4d67-8a9b-a6981176226e.png)
