### ISSUE TITLE
Q: Is there a straightforward way to add custom functions and buttons?

### ISSUE THREAD

**Issue by DoDzilla-ai** [man-group/dtale#562]
I was looking for a simple GUI that will allow users to tinker with data and apply my custom functions to it. I found DTale and this looked like what I was looking for. Until I couldn't figure out how to add my own custom functions to the UI. I guess I need to dig in both front-end and back-end files of dtale to add my custom button and attach a function to it. I was wondering if there is any straightforward way to do this? 

**Exactly what I want to do:**
I want to allow users to change some cells in their dataframe and allow them to apply clustering on the modified data. I was planning to create a flask back-end for it. I don't need them to see the results from DTale UI.  

PS: There is [this](https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md) read me file which allows me to run it via flask but I don't know the ins/outs of flask side of DTale.

**Comment by aschonfeld** [comment]
So you can simply use D-Tale for the grid display & cell editing just by following that [example](https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md).  But what I think you'd want is to have an `<iframe>` holding your D-Tale grid.  So that way you can see the grid on your screen and edit cells, but then have buttons surrounding the `<iframe>` which call your clustering functions.

Something really simple like:
```
<html>
  <body>
    <iframe src="/dtale/main/1" />
    <form method="POST" action="/load-clustering">
      <input type="submit" name="submit_button" value="Apply Clustering" />
    </form>
  </body>
</html>
```

And in your flask code you'd add a route similar to:
```
from dtale.app import get_instance

@app.route("/load-clustering", methods=["POST"])
def load_clustering():
  df = get_instance("1").data
  clustering_function(df)
  ...
```

Now there is obviously a lot more work to be done to make your app pretty looking, but that is the gist of it.  You'll probably want to add some code to load your initial data (which users edit) into D-Tale on startup of your app.

If you want I can try building a little proof-of-concept in the next few days (obviously minus the clustering code, you can plug that in later)

**Comment by DoDzilla-ai** [comment]
I am talking with a friend of mine to get help for the front-end side. I am a back-end guy :) I hope I can get it working.

**Comment by aschonfeld** [comment]
Terrific, well keep me posted and message me if you get stuck. Also, if you havent already, please toss your ⭐️ on the repo. Thanks 🙏
