### ISSUE TITLE
Standalone mode - app-root seems not correctly populated when running  dtale via cli ?

### ISSUE THREAD

**Issue by nsteinmetz** [man-group/dtale#586]
Hello,

I try to deploy dtable behind a reverse proxy, under `/apps/dtale/*`

So I basically have the following `Dockerfile`

```
FROM python:3.8.10
RUN pip install dtale==1.58.3
```

What I expect is that when I run dtale container like:

```
docker run -ti dtale dtale --app-root /apps/
```

It should be accessible via http://localhost:40000/apps/

What I notice:
* Statics (css, etc) are called with the the `/apps/` in their path but it leads to 404 ; if we use the path without the app-root, it works as expected (ie as if it was not set)
* `/dtale/upload` is called correctly (but not related to `/apps/`) but layout is missing (due to 404)

So it looks in this mode, app-root is partially ignored or not well interprted.

`--app-root` becomes `app_root` from :
* https://github.com/man-group/dtale/blob/master/dtale/cli/script.py#L48 and 
* https://github.com/man-group/dtale/blob/master/dtale/cli/script.py#L153

I don't want to expose dtable behind jupyter proxy as I don't use it - I would prefer directly behind my reverse proxy.

Do you see what is missing here ? 

Reading at the code, I don't see yet why it does'nt work as expected...

**Comment by aschonfeld** [comment]
So just a quick note on the `--app-root` parameter.  That parameter exists in case you're running something like[jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) which will allow you to hit any running API or webapp through a predefined proxy path.  So the idea is that D-Tale will still run in its normal fashion (http://[hostname]:40000/dtale/main/1) but you can also hit it using the proxy path (http://[hostname]/user/[username]/proxy/40000/dtale/main/1).  Under the hood, D-Tale is simply using the value of `app_root` (which in the case of jupyter-server-proxy will be something like '/user/[username]/proxy/40000/') to adjust how things are routed in the HTML (stuff like api routes and fetching static resources) so that it can use this path.

So my next question is, what are you using as a proxy?  Something other than jupyter-server-proxy?  If you're not suing a proxy service and are simply trying to change the path the D-Tale uses then I think what you'll want to do is create you're Flask application which extends D-Tale and specify your own custom route.  Here's some [documentation](https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md) on how to do that.

Hope this helps and I'm happy to answer any additional questions. Also, if you haven't already, please toss your ⭐ on the repo.  Thanks 🙏
