### ISSUE TITLE
Describe chart type does not persist

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [man-group/dtale#600]
In the describe feature it is really annoying if I want to look at histograms that every time I select a new column the chart resets to the default box plot and I have to re-click the histogram button. I suggest having the user selected chart type persist so long as it is valid for the current data type when iterating over columns.

**Comment by aschonfeld** [comment]
@marcel-goldschen-ohm good call.  I'll work on changing this now and let you know when its ready

**Comment by aschonfeld** [comment]
So I was able to update the code so that as you switch columns it will maintain which chart you had selected previously.  The only hitch is that when you toggle to a column which doesn't have the chart you previously had selected it will default back to the Boxplot.  There's no real way around that unfortunately.

**Comment by aschonfeld** [comment]
Just released v1.61.1 to pypi (conda-forge will available shortly) which includes this update. If you haven't already, please toss your ⭐ on the repo.  Thanks 🙏

**Comment by marcel-goldschen-ohm** [comment]
Nice! Thanks.
