### ISSUE TITLE
Missing Analysis chart not able to show Chinese Characters

### ISSUE THREAD

**Issue by automano** [man-group/dtale#607]
I try to use the Missing Analysis in dtale, but chart not able to show Chinese characters. And headers of my csv file are Chinese characters title. In chart, they are all blank.

The dtale and python version:

dtale                     1.61.1
python                    3.8.12

![Snipaste_2021-12-09_15-42-26](https://user-images.githubusercontent.com/17286982/145354631-f9d442bc-076b-4c07-8cb4-7fe5665230a1.png)

**Comment by aschonfeld** [comment]
@automano I dug a little deeper and found that this is an issue with the `missingno` package in python.  I've passed the issue over to them https://github.com/ResidentMario/missingno/issues/155

**Comment by ResidentMario** [comment]
`missingno` uses `matplotlib`, and `matplotlib` uses a default font that doesn't define Chinese glyphs.

In order to fix this, follow the instructions [here](https://stackoverflow.com/questions/39630928/how-to-plot-a-figure-with-chinese-characters-in-label) and/or [here](https://jdhao.github.io/2017/05/13/guide-on-how-to-use-chinese-with-matplotlib/).

While this _is_ a little surprising, I am not in support of messing with the font choices `matplotlib` makes in `missingno`. Afraid you'll have to use a workaround.

**Comment by ResidentMario** [comment]
Ah, I see this is an online GUI tool. In that case @aschonfeld you can probably fiddle with the relevant settings.

**Comment by aschonfeld** [comment]
@ResidentMario thanks for the tip, I was able to solve it using the following:

```
import matplotlib
import matplotlib.pyplot as plt

plt.rcParams["font.sans-serif"] = ["SimHei"]  # Or any other Chinese characters
matplotlib.rcParams["font.family"] = ["Heiti TC"]
```

**Comment by aschonfeld** [comment]
@automano just release v2.1.0 with this fix.  Let me know if you have any other issues
