### ISSUE TITLE
Display data frame name in browser tab instead of device_name:port/dtale/main/X

### ISSUE THREAD

**Issue by HeinrichGraser** [man-group/dtale#614]
I was wondering whether you considered to let the user set a flag in the dtale.show() function to show the name of the data frame that is opened in d-tale, instead of the device_name:port/dtale/main/X.
The reason I am asking for that is that currently, I am comparing many data frames with each other with the help of your really great tool, but I always get confused after a while, which tab is which data frame. To resolve my confusion, I suggest adding a flag to e.g. the dtale.show() function like "display_dataframe_name", which would then show the data frame name in the browser instead of the above.
In case that is not possible due to the URL required for opening the tab, could you replace the number of the dtale instance with  the dataframe name? Like device_name:port/dtale/main/data_frame?

**Comment by aschonfeld** [comment]
@HeinrichGraser funny you should mention this functionality because I used to support this, but had to remove it due to some refactoring to the data storage layer.  I can look into adding this back. 

So the way I envision it working is that if you call

```
import dtale
import pandas as pd

dtale.show(pd.DataFrame([1,2,3,4,5]), name='foo')
```

The message printed in your console will be: `http://[hostname]:40000/dtale/main/foo`

And you can hit your D-Tale instance using either `http://[hostname]:40000/dtale/main/foo` or `http://[hostname]:40000/dtale/main/1` (this number depends on when your data was loaded)

**Comment by aschonfeld** [comment]
@HeinrichGraser this functionality is currently available for the example above if you change your URL to `http://[hostname]:40000/dtale/main/name/foo`

**Comment by aschonfeld** [comment]
@HeinrichGraser just added this functionality back in v2.1.0
