### ISSUE TITLE
404 error using D-Tale + Jupyter Server Proxy

### ISSUE THREAD

**Issue by bazils2** [man-group/dtale#622]
Hi team, thanks for your app, it seems very useful for EDA and easy to use.

It works just fine on a local machine, but when i start to use it on a server, can't get an app working.

Without using Jupyter Server Proxy i just get white blank screen, as in some other issues.

Then i Installed Jupyter Server Proxy, so now i get '404 : Not Found'  error instead of a white screen. Could you help me to run thing properly?

Server: CentOS Linux 7
JupyterLab: Version 3.2.1

Server is a fresh installed CentOS machine in a private network, i have sudo rights.

I connect to server from local machine via ssh tunnel on 8080 port.

**Comment by cmosguy** [comment]
@bazils2  I am getting the same error on ubuntu, did you find a solution to your issue?

**Comment by ricmatsui** [comment]
It looks like the issue is related to how `final_app_root` is determined since the `JUPYTER_SERVER_PROXY` flag is for a JupyterHub setup and not for a standalone JupyterLab setup:

https://github.com/man-group/dtale/blob/624ef41a289d8e2c6ffc05eb700080b52ad7b2e8/dtale/app.py#L569-L577

For a standalone JupyterLab, the URL should be `/proxy` instead of `/user/<user>/proxy` as described in the Jupyter Server Proxy docs: https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html#without-jupyterhub.

As a workaround, launching JupyterLab with the `JUPYTERHUB_SERVICE_PREFIX` environment variable set as `/proxy` which is checked by D-Tale does fix the 404 error for me.

**Comment by cmosguy** [comment]
Thanks @ricmatsui  that helped me!

**Comment by aschonfeld** [comment]
@ricmatsui thanks so much for the help 🙏

**Comment by maxant** [comment]
Thanks for the solution with the env var!

Very strangely, I also had to tweak `/etc/hosts` so that `localhost` points to my docker container IP address. I did that using `docker run ... -h localhost`.  I wonder if it is because the dtale server is bound to the IP address rather than localhost or 0.0.0.0?  Not sure, happy enough with that solution though as it seems to work well.

**Is it worth mentioning this problem and its solution on the main readme?**

If it helps anyone, here is my docker file and how i build & run it:

```
################################################################################
# builds a base image with the jdk & python3, and Delta Lake and some tools
################################################################################
# docker build -f DockerfileJdk11PythonDeltaLake -t jdk11pythondeltalake .

FROM apache/spark:3.5.0-scala2.12-java11-python3-r-ubuntu

USER root

RUN apt update
RUN apt autoremove -y
RUN apt upgrade -y
RUN pip install pandas
RUN pip install pyarrow
RUN pip install delta-spark
RUN pip install requests
RUN pip install jupyterlab
RUN pip install notebook
RUN pip install voila
RUN pip install sparksql-magic
RUN pip install matplotlib

RUN pip install dtale
RUN pip install jupyter-server-proxy

ENV TZ="Europe/Zurich"
```

generate a password: https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html

```
    docker run \
        --rm -it \
        -v "/home/ant/jupyter-config:/root/.jupyter:rw" \
        --network n001 \
        --name jupyter \
        -w /home/jovyan \
        jdk11pythondeltalake \
        jupyter lab password
```

Then run the container:

```
    docker run \
        -d --restart unless-stopped \
        -v "/home/ant/jupyter:/home/jovyan:rw" \
        -v "/home/ant/jupyter-config:/root/.jupyter:rw" \
        -v "/home/ant/.ivy2:/root/.ivy2:rw" \
        -e "SPARK_NO_DAEMONIZE=true" \
        -e "JUPYTERHUB_SERVICE_PREFIX=/proxy" \
        --network n001 \
        --name jupyter \
        -m 1024m --cpus="4" \
        -p 127.0.0.1:18240:8888 \
        -p 127.0.0.1:18241:4042 \
        -w /home/jovyan \
        -h localhost \
        jdk11pythondeltalake \
        jupyter server \
            --allow-root \
            --ip 0.0.0.0 \
            --no-browser
```

And now login at http://localhost:18240/lab
