### ISSUE TITLE
BUG: Can not set up a developer environment with Docker or without Docker.

### ISSUE THREAD

**Issue by toshiakiasakura** [man-group/dtale#672]
I tried to set up a developer environment wiht or without Docker. 

I frst tried Docker command by 
```
yarn run build
docker-compose build dtale_3_6
```
However, d3-array and node incompatibility erro was raised. 
```
+ yarn install --frozen-lockfile
yarn install v1.16.0
[1/4] Resolving packages...
warning Resolution field "d3-array@2.3.3" is incompatible with requested version "d3-array@^2.5.0"
[2/4] Fetching packages...
error highlight.js@11.5.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.16.0"
error Found incompatible module.
```
After I changed d3-array package version in `package.json`, and node version of `Dockerfile`, I can proceed `docker-compose.yaml`. However, since `Dockerfile` include the line `  ; python setup.py test \` and this is very heavy and my laptop PC (not high spec) was crashed...

Then, I switched to local set up without Docker. Installing has never been a problem now, but after running
```
 dtale --csv-path ./tests/dataset/titanic.csv
```
It displayed url for server, but it raised the following error.
```
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/toshiaki/Desktop/PyPI/dtale_dev/dtale/dtale/views.py", line 1162, in view_main
    return _view_main(data_id)
  File "/home/toshiaki/Desktop/PyPI/dtale_dev/dtale/dtale/views.py", line 1147, in _view_main
    return base_render_template("dtale/main.html", data_id, title=title, iframe=iframe)
  File "/home/toshiaki/Desktop/PyPI/dtale_dev/dtale/dtale/views.py", line 1110, in base_render_template
    if not len(os.listdir("{}/static/dist".format(os.path.dirname(__file__)))):
FileNotFoundError: [Errno 2] No such file or directory: '/home/toshiaki/Desktop/PyPI/dtale_dev/dtale/dtale/static/dist'
```

Then, I can not come up with any further trials to prepare a developmental environemnt. 
Can anyone help me???

**Comment by aschonfeld** [comment]
@toshiakiasakura apologies for the issues.  Since your computer doesn't seem to have the necessary power for building docker images I'd continue down the path of developing without it.

So first thing, I install something call [nvm]( https://github.com/nvm-sh/nvm) this will allow you to install multiple versions of node on your machine and switch back & forth between them.  Locally I have the following setup:
```
node: v17.0.1
npm: 8.0.1
yarn: 1.22.17
```

Once you have an up-to-date version of those installed you can navigate to the `frontend folder and run the following:
```
npm install
npm run watch
```

This will serve up your compiled JS on the fly and if you make any changes it will recompile and serve those updates up as well.

Once that is complete navigate back up one folder to the main location you cloned D-Tale to.  Then assuming you have a virtual environment activated (which based on your previous comment you do) you can run the following:
```
python setup.py develop
```
This will install the current D-Tale code into your virtual environment.  And once that is complete you should be able to run your command: `dtale --csv-path ./tests/dataset/titanic.csv`

Side note: if you're still having issues you can try doing a `pip uninstall dtale` before running `python setup.py develop` just to make sure theres no stale artifacts installed in your environment.

Hope this helps.  Let me know if theres any more issues.

**Comment by toshiakiasakura** [comment]
Thanks! I successfully launched up the develop environment. 
I used `nodebrew` to change version of nodes, and maybe my problem was caused from version discrepancy of node.

Note: 
It seems `./tests/dataset/titanic.csv` is moved to `./tests/data/titanic.csv`.

**Comment by aschonfeld** [comment]
Good catch, i’ll make sure to update the filepath to the titantic dataset

**Comment by matrach** [comment]
Hi!

I've had a similar problem and found [nodeenv](https://pypi.org/project/nodeenv/) that could use Python's virtualenv to manage node version too.

While being in a virtualenv, one may install the specified node version with:
```bash
pip install nodeenv
nodeenv --node=17.0.1 -p
```

Then continue as indicated in the readme. Maybe this could be added to the instructions for people not familiar with developing in nodejs, just like me?

---
Nevertheless, `npm install` still failed for me with:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: dtale@2.6.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.9 || ^15.3.0 || ^16.0.0" from react-motion@0.5.2
npm ERR! node_modules/react-motion
npm ERR!   react-motion@"0.5.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

As indicated in the message, `npm install --legacy-peer-deps` succeeded.
