### ISSUE TITLE
Horizontal scrollbar on data view not synced with mouse

### ISSUE THREAD

**Issue by Gdsimms** [man-group/dtale#799]
I don't know if this is a dtale issue only, or if it is a browser issue (Chrome), but when I grab the horizontal scroll bar to go to the rightmost columns, my mouse cursor drags faster than the scrollbar moves and I have to go back and re-grab the scrollbar several times to get to the right. I don't recall having this issue with any other software or website, but it happens all the time with dtale tabs. Scrolling to the left does not have this issue. 

https://github.com/man-group/dtale/assets/8623189/4e5b1798-5159-4018-94ba-88df9a3d4464

**Comment by aschonfeld** [comment]
So unfortunately I don't think there is a way around this.  It is not due to your browser but the way that the data is rendered on the screen and how the sizing is calculated.  So when viewing the grid only the cells that are visible on the screen is what is actually drawn and then the amount left to be scrolled is based on the columns that haven't been rendered.  But the problem is that since we haven't loaded the data for the hidden columns (for performance reasons) we can't come up with an exact measurement on how wide these columns are so it's using a default width to determine how much scrolling is required.  So as you scroll it loads these columns and figures out the real widths, thus making the scrollbar come out of sync.

Now if there was an easy way to determine the widths of the columns on the backend and return that to the screen then we could solve this.  I don't know of any package that will do this and I also don't believe that what will be gained by fixing this problem won't actually be worth the effort that it takes to solve it.  Just being honest.

I apologize for the annoyance of the bug.

**Comment by Gdsimms** [comment]
Ok. Dispose of the issue as you see fit. Thanks for taking the time to explain.
