### ISSUE TITLE
Create "Select All" option when selecting Duplicates

### ISSUE THREAD

**Issue by aschonfeld** [man-group/dtale#847]
When there are so many variables, it can be really tiring to choose each one one by one. It would be great if there was an option to select all to see and delete duplicate rows.

_Originally posted by @T-a-c-h-y-o-n in https://github.com/man-group/dtale/issues/840#issuecomment-1893251142_

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n any chance you can send an example where you have a lot of variables in the duplicates popup?  So far only instance I can see is when you have "Show Duplicates" selected for example:
![image](https://github.com/man-group/dtale/assets/11547371/65e7e292-5d7c-428f-80d6-3aa714bb173e)

**Comment by T-a-c-h-y-o-n** [comment]
Hello, the problem here is to enter each variable one by one to find the duplicate values ​​in many variables. Frankly, I don't fully understand your question. But it would be nice if there was an option to select all at the bottom of the column(s) section in that image, instead of selecting them one by one, and they would all appear in that section.

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n Ok, now I understand. Thank you

**Comment by aschonfeld** [comment]
how's this? Also this is only for "Show Duplicates" do I need to add this button to the other duplicate operations

https://github.com/man-group/dtale/assets/11547371/f0c48fcf-c0c8-476d-b59e-32d8317a0093

**Comment by T-a-c-h-y-o-n** [comment]
It's great, just what we wanted.

**Comment by aschonfeld** [comment]
@T-a-c-h-y-o-n this feature has been added in v3.12.0.  Let me know if you have any issues.
