### ISSUE TITLE
Build Column with Random number

### ISSUE THREAD

**Issue by reza1615** [man-group/dtale#92]
It would be helpful to create a new column with Random in range number or Random Characters

**Comment by reza1615** [comment]
@aschonfeld : I created attached file for random
 'Rand_float',
'Rand_int',
'Rand_choice',
'Rand_bool', 
'Rand_str', 
'Rand_date'
After creating the code I saw you also worked on this part  :(. anyway My code has some more random like date, string, choice,..
[Create Random Column.zip](https://github.com/man-group/dtale/files/4389988/Create.Random.Column.zip)

**Comment by aschonfeld** [comment]
I’ll see if I can implement choice, bool & date tomorrow.  So far i managed to implement float, int & string for my next release.

**Comment by reza1615** [comment]
@aschonfeld : Float function for minus numbers may have a problem why you don't use 
np.random.uniform(start, end, num)

**Comment by aschonfeld** [comment]
Oh yea, I completely forgot about that function.  I used that in one my previous projects too.  Good catch!

**Comment by aschonfeld** [comment]
@reza1615 thisjupyter notebook is great! thank you for sending that over. One change that I was going to make was that when generating random integers I was going to use `np.random.random_integers` instead of `np.random.randint` because I believe that is the one that will generate them uniformly similar to floats.

Also, for the choice generator would it be fine for me to allow users to specify a comma-separated string which I'll turn into a list for the choices?  Just less work then building out a whole UI around build a list of values. 🙏 

Lastly, for the random date generation I was thinking of doing this:
```
dates = pd.date_range(start, end).to_list()
dates = [dates[i] for i in np.random.random_integers(0, len(dates) - 1, size=len(df))]
```

Might want to add an option for whether they want business days or not. Also if they want timestamps this was the code I was using:
```
def pp(start, end, n):
        start_u = start.value//10**9
        end_u = end.value//10**9
        return pd.DatetimeIndex((10**9*np.random.randint(start_u, end_u, n, dtype=np.int64)).view('M8[ns]'))

timestamps = pp(pd.Timestamp(start), pd.Timestamp(end), len(df))
```

**Comment by aschonfeld** [comment]
Nevermind, looks like `numpy.random.randint` is uniformly distributed as well.

**Comment by reza1615** [comment]
> Nevermind, looks like `numpy.random.randint` is uniformly distributed as well.

![image](https://user-images.githubusercontent.com/2202483/77800026-660a5500-704c-11ea-98f7-2c9bddfcf6a9.png)

random_integers is deprecated and replaced by randint

**Comment by aschonfeld** [comment]
Yep, i switched it back 👍

**Comment by aschonfeld** [comment]
added in v1.8.1
